// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6ZuVY7e1M4Aumam9k8ixep74qTi1xPfg',
    appId: '1:221677627497:web:2c44dce177ce6b242c1af8',
    messagingSenderId: '221677627497',
    projectId: 'quiz-app-ad290',
    authDomain: 'quiz-app-ad290.firebaseapp.com',
    storageBucket: 'quiz-app-ad290.firebasestorage.app',
    measurementId: 'G-G58HNSCWZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALsJNN_uUBo9K173Jh6jtH0btK2PWd6O4',
    appId: '1:221677627497:android:b6e526bd4eb61f2a2c1af8',
    messagingSenderId: '221677627497',
    projectId: 'quiz-app-ad290',
    storageBucket: 'quiz-app-ad290.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcPC8pBDuI1x8O7vvP1IHcIMVt5q4IbBA',
    appId: '1:221677627497:ios:bef369ced3d1f9962c1af8',
    messagingSenderId: '221677627497',
    projectId: 'quiz-app-ad290',
    storageBucket: 'quiz-app-ad290.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcPC8pBDuI1x8O7vvP1IHcIMVt5q4IbBA',
    appId: '1:221677627497:ios:bef369ced3d1f9962c1af8',
    messagingSenderId: '221677627497',
    projectId: 'quiz-app-ad290',
    storageBucket: 'quiz-app-ad290.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6ZuVY7e1M4Aumam9k8ixep74qTi1xPfg',
    appId: '1:221677627497:web:4301a47318adcdbf2c1af8',
    messagingSenderId: '221677627497',
    projectId: 'quiz-app-ad290',
    authDomain: 'quiz-app-ad290.firebaseapp.com',
    storageBucket: 'quiz-app-ad290.firebasestorage.app',
    measurementId: 'G-WSZT7GBMKH',
  );
}
